// Generated by scripts/build_admin.py; edit .mjs sources.
(() => {
'use strict';
try {
// admin/config.mjs
// Public browser configuration. No passwords, service_role or secret keys here.
const config = Object.freeze({
  url: 'https://hvarqatfpcwnxhsulxuu.supabase.co',
  publishableKey: 'sb_publishable_m39CXb6MUsMrHJI9KHI_Kg_Nsta9ec7',
});

// components/public-players.mjs
function applyPublicPlayers(doc, players, siteRoot, win) {
 const profiles=Object.fromEntries(players.map(p=>[p.id,p]));
 win.LPL_PLAYERS={...win.LPL_PLAYERS,...profiles};
 for(const n of doc.querySelectorAll('[data-live-player]')){
  const p=profiles[n.dataset.livePlayer];if(!p)continue;
  const value=p[n.dataset.liveField];if(typeof value!=='string')continue;
  const text=(n.dataset.liveFormat||'{value}').replace('{value}',value);
  if(n.textContent!==text)n.textContent=text;
 }
 for(const n of doc.querySelectorAll('[data-live-avatar]')){
  const p=profiles[n.dataset.liveAvatar];if(!p)continue;
  let src=null;
  if(/^assets\/[a-zA-Z0-9_./-]+$/.test(p.avatar)&&!p.avatar.includes('..'))src=new URL(p.avatar,siteRoot).href;
  else{try{const url=new URL(p.avatar);if(url.protocol==='https:'&&!url.username&&!url.password)src=url.href;}catch{}}
  if(src&&n.src!==src)n.src=src;
  if(n.alt)n.alt=p.nickname;
 }
 for(const n of doc.querySelectorAll('[data-live-aria]')){
  const p=profiles[n.dataset.liveAria];if(p)n.setAttribute('aria-label','Профиль '+p.nickname);
 }
 win.dispatchEvent(new win.Event('lpl:players-updated'));
}
if(typeof document!=='undefined'){
 const script=document.currentScript;
 const root=new URL('../',script.src);
 let loading=false;
 async function refresh(){
  if(loading)return;loading=true;
  const abort=new AbortController();const timer=setTimeout(()=>abort.abort(),10000);
  try{
   const response=await fetch(config.url+'/rest/v1/rpc/site_players',{method:'POST',headers:{apikey:config.publishableKey,'Content-Type':'application/json'},body:'{}',cache:'no-store',signal:abort.signal});
   if(!response.ok)throw new Error('profiles_unavailable');
   const players=await response.json();
   if(!Array.isArray(players)||!players.every(p=>typeof p.id==='string'&&typeof p.nickname==='string'))throw new Error('invalid_profiles');
   applyPublicPlayers(document,players,root,window);
   document.documentElement.dataset.profilesSource='supabase';
  }catch{
   // Preserve the pre-rendered site when offline or before migration 003 is installed.
   document.documentElement.dataset.profilesSource='static-fallback';
  }finally{clearTimeout(timer);loading=false;}
 }
 refresh();
 document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh();});
 window.addEventListener('pageshow',event=>{if(event.persisted)refresh();});
}

} catch (error) {
const message = document.getElementById('login-message');
if (message) { message.textContent = 'Не удалось запустить форму входа. Обновите страницу; если ошибка повторяется, сообщите нам.'; message.className = 'status-error'; }
}
})();
