// Generated by scripts/build_admin.py; edit .mjs sources.
(() => {
'use strict';
try {
// admin/config.mjs
// Public browser configuration. No passwords, service_role or secret keys here.
const config = Object.freeze({
  url: 'https://hvarqatfpcwnxhsulxuu.supabase.co',
  publishableKey: 'sb_publishable_m39CXb6MUsMrHJI9KHI_Kg_Nsta9ec7',
});

// admin/api.mjs
class ApiError extends Error {
  constructor(message, status = 0) { super(message); this.status = status; }
}

// Deliberately memory-only sessions: reloading this first version requires login.
// Neither passwords nor access/refresh tokens are written to browser storage.
class LeagueApi {
  constructor(config, fetcher = globalThis.fetch.bind(globalThis)) {
    this.config = config;
    this.fetcher = fetcher;
    this.token = null;
    this.expiresAt = 0;
  }
  clearSession() { this.token = null; this.expiresAt = 0; }
  async request(path, {method = 'GET', body, authorized = true, headers = {}} = {}) {
    if (authorized && (!this.token || Date.now() >= this.expiresAt)) {
      throw new ApiError('Сессия закончилась. Войдите снова.', 401);
    }
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), 20000);
    let response;
    let data;
    try {
      response = await this.fetcher(this.config.url + path, {
        method, signal: controller.signal, credentials: 'omit', cache: 'no-store',
        headers: {
          apikey: this.config.publishableKey,
          ...(authorized ? {Authorization: `Bearer ${this.token}`} : {}),
          ...(body !== undefined ? {'Content-Type': 'application/json'} : {}), ...headers,
        },
        ...(body !== undefined ? {body: JSON.stringify(body)} : {}),
      });
      data = await response.json().catch(() => null);
    } catch {
      throw new ApiError('Нет ответа от сервера. Проверьте соединение. Если вы сохраняли изменения, загрузите запись заново, прежде чем повторять сохранение.');
    } finally { clearTimeout(timer); }
    if (!response.ok) {
      let message = 'Не удалось выполнить запрос. Попробуйте ещё раз.';
      if (response.status === 401) message = 'Сессия закончилась или вход не подтверждён. Войдите снова.';
      if (response.status === 403 || data?.code === '42501') message = 'Нет прав для этой операции. Проверьте права администратора.';
      if (response.status === 409) message = 'Запись с таким идентификатором уже существует или связана с другими данными.';
      if (response.status === 429) message = 'Слишком много попыток. Подождите немного.';
      if (data?.code === 'invalid_credentials') message = 'Неверная почта или пароль.';
      if (data?.code === 'email_address_not_authorized' || data?.msg === 'Email address not authorized') message = 'Отправка писем участникам ещё не настроена. Организатору нужно подключить SMTP в Supabase.';
      if (data?.code === 'over_email_send_rate_limit') message = 'Достигнут лимит писем. Подождите и попробуйте позже.';
      if (data?.code === 'weak_password') message = 'Пароль не соответствует настройкам проекта. Используйте более длинный пароль с буквами и цифрами.';
      if (data?.code === 'email_not_confirmed') message = 'Почта не подтверждена. Проверьте аккаунт в Supabase Authentication.';
      if (data?.code === '23514' || data?.code === '22P02') message = 'Проверьте значения полей: база отклонила некорректные данные.';
      if (data?.code === 'PGRST202') message = 'Новая функция ещё не установлена. Выполните миграцию участников и голосования в Supabase.';
      if (data?.code === '23505') message = 'Этот игрок уже привязан к другому аккаунту.';
      const explanations = {
        owner_required: 'Эта операция доступна только главному администратору.',
        owner_protected: 'Нельзя изменить права главного администратора.',
        approved_member_required: 'Для голосования нужно подтверждение владельца и привязка к игроку.',
        player_binding_required: 'Выберите игрока для подтверждённого участника.',
        player_binding_locked: 'Привязка игрока уже закреплена. Её нельзя менять из пульта.',
        email_confirmation_required: 'Сначала подтвердите почту аккаунта.',
        ballot_not_open: 'Голосование уже закрыто или ещё не открыто.',
        ballot_not_closed: 'Сначала закройте голосование.',
        ballot_already_exists: 'Голосование по этому матчу уже создано.',
        candidate_not_in_match: 'Этот игрок не участвовал в матче.',
        completed_match_required: 'Нужен завершённый опубликованный матч.',
        complete_roster_required: 'Состав матча должен содержать 10 игроков.',
        choose_leading_candidate: 'Выберите одного из игроков с наибольшим числом голосов.',
        no_votes: 'Нет голосов. Подтвердить результат нельзя.',
        admin_must_be_approved: 'Для выдачи админки сначала подтвердите участника.',
      };
      if (explanations[data?.message]) message = explanations[data.message];
      throw new ApiError(message, response.status);
    }
    return data;
  }
  async signIn(email, password, requireAdmin = true) {
    this.clearSession();
    const session = await this.request('/auth/v1/token?grant_type=password', {
      method: 'POST', body: {email, password}, authorized: false,
    });
    if (!session?.access_token || !session.expires_in) throw new ApiError('Сервер не вернул сессию.');
    this.token = session.access_token;
    this.expiresAt = Date.now() + session.expires_in * 1000 - 5000;
    try { if (requireAdmin) {
      const isAdmin = await this.request('/rest/v1/rpc/is_league_admin', {method: 'POST', body: {}});
      if (isAdmin !== true) throw new ApiError('Этот аккаунт не назначен администратором.', 403);
    } } catch (error) { await this.signOut(); throw error; }
    return session.user?.email || email;
  }
  async signUp(email, password, displayName, redirectUrl) {
    if (password.length < 10) throw new ApiError('Пароль должен содержать не менее 10 символов.');
    const name = displayName.trim();
    if (!name || name.length > 80) throw new ApiError('Укажите имя или ник: от 1 до 80 символов.');
    const query = redirectUrl && /^https?:\/\//.test(redirectUrl) ? '?redirect_to=' + encodeURIComponent(redirectUrl) : '';
    await this.request('/auth/v1/signup' + query, {method:'POST', authorized:false, body:{email,password,data:{display_name:name}}});
    // Always use the explicit login flow, including when confirmations are disabled.
  }
  rpc(name, body = {}, authorized = true) {
    if (!['member_me','owner_members','owner_update_member','manage_mvp_ballot','cast_mvp_vote','mvp_ballot','mvp_match_list','member_points'].includes(name)) throw new ApiError('Неизвестная операция.');
    return this.request('/rest/v1/rpc/' + name, {method:'POST',body,authorized});
  }
  async signOut() {
    try {
      if (this.token && this.expiresAt > Date.now()) await this.request('/auth/v1/logout?scope=local', {method: 'POST'});
    } catch { /* Local credentials must be cleared even if the server is unreachable. */ }
    finally { this.clearSession(); }
  }
  async list(table) {
    const sorts = {players: 'display_order.asc,id.asc', news: 'display_order.asc,id.asc', matches: 'day.asc,id.asc', seasons: 'id.asc', league_settings: 'singleton.asc'};
    if (!sorts[table]) throw new ApiError('Неизвестный раздел.');
    return this.request(`/rest/v1/${table}?select=*&order=${sorts[table]}`);
  }
  async update(table, original, values) {
    if (!['players', 'news'].includes(table)) throw new ApiError('Редактирование раздела пока не подключено.');
    // Compare all editable fields in the same PATCH: don't silently overwrite another editor.
    const query = new URLSearchParams({id: `eq.${original.id}`, select: '*'});
    for (const key of Object.keys(values)) {
      const value = original[key];
      if (value === null) query.set(key, 'is.null');
      else {
        const raw = typeof value === 'object' ? JSON.stringify(value) : String(value);
        query.set(key, `eq.${JSON.stringify(raw)}`);
      }
    }
    const result = await this.request(`/rest/v1/${table}?${query}`, {
      method: 'PATCH', body: values, headers: {Prefer: 'return=representation'},
    });
    if (!Array.isArray(result) || result.length !== 1) {
      throw new ApiError('Запись изменилась в другой вкладке или доступ отозван. Скопируйте свой текст и откройте запись заново.', 409);
    }
    return result[0];
  }
}

function avatarUrl(value, base) {
  if (/^assets\/[a-zA-Z0-9_./-]+$/.test(value) && !value.includes('..')) return new URL('../' + value, base).href;
  try { const url = new URL(value); if (url.protocol === 'https:' && !url.username && !url.password) return url.href; } catch {}
  return null;
}

function playerValues(form, base) {
  const nickname = String(form.nickname || '').trim();
  const avatar = String(form.avatar || '').trim();
  const quote = String(form.quote || '').trim();
  const display_order = Number(form.display_order);
  if (!nickname || nickname.length > 80) throw new ApiError('Ник должен содержать от 1 до 80 символов.');
  if (!avatarUrl(avatar, base)) throw new ApiError('Фото: укажите путь assets/имя.jpg или полный HTTPS-адрес.');
  if (!Number.isInteger(display_order) || display_order < 0) throw new ApiError('Порядок должен быть целым числом от 0.');
  return {nickname, avatar, quote, display_order};
}
function newsValues(form) {
  const title = String(form.title || '').trim();
  const paragraphs = String(form.paragraphs || '').trim().split(/\n\s*\n/).map(p => p.trim()).filter(Boolean);
  const display_order = Number(form.display_order);
  if (!title || !paragraphs.length) throw new ApiError('Заполните заголовок и текст новости.');
  if (!Number.isInteger(display_order) || display_order < 0) throw new ApiError('Порядок должен быть целым числом от 0.');
  if (!['draft', 'published'].includes(form.publication_status)) throw new ApiError('Выберите статус новости.');
  return {
    title, paragraphs, display_order, label: String(form.label || '').trim(),
    short_title: String(form.short_title || '').trim() || null,
    excerpt: String(form.excerpt || '').trim() || null,
    quote_player_id: form.quote_player_id || null, publication_status: form.publication_status,
  };
}

// admin/app.mjs

const api = new LeagueApi(config);
const $ = id => document.getElementById(id);
const state = {section: 'players', selected: null, records: {}, dirty: false, busy: false, me: null};
const names = {players: 'Игроки', news: 'Новости', matches: 'Матчи', members: 'Участники и доступ'};
function node(tag, text, className) {
  const el = document.createElement(tag);
  if (text !== undefined && text !== null) el.textContent = text;
  if (className) el.className = className;
  return el;
}
function message(text = '', error = false, id = 'status') {
  $(id).textContent = text;
  $(id).className = error ? 'status-error' : 'status-success';
}
function busy(value) {
  state.busy = value;
  for (const el of document.querySelectorAll('button, #editor input, #editor textarea, #editor select')) el.disabled = value;
  $('workspace').setAttribute('aria-busy', String(value));
}
function mayLeave() {
  return !state.dirty || window.confirm('Есть несохранённые изменения. Оставить их без сохранения?');
}
window.addEventListener('beforeunload', event => {
  if (state.dirty || state.busy) { event.preventDefault(); event.returnValue = ''; }
});

$('login-form').addEventListener('submit', async event => {
  event.preventDefault();
  if (state.busy) return;
  busy(true);
  message('Проверяем доступ…', false, 'login-message');
  const fields = new FormData(event.currentTarget);
  try {
    const email = await api.signIn(String(fields.get('email')).trim(), fields.get('password'));
    await loadData();
    $('account').textContent = email;
    $('login').hidden = true;
    $('workspace').hidden = false;
    $('logout').hidden = false;
    state.dirty = false;
    state.selected = null;
    state.section = 'players';
    showSection();
    message('');
  } catch (error) {
    await api.signOut();
    message(error.message, true, 'login-message');
  } finally {
    event.target.elements.password.value = '';
    busy(false);
  }
});
$('logout').addEventListener('click', async () => {
  if (state.busy || !mayLeave()) return;
  busy(true);
  await api.signOut();
  state.records = {};
  state.dirty = false;
  state.selected = null;
  $('editor').replaceChildren();
  $('records').replaceChildren();
  $('account').textContent = '';
  $('workspace').hidden = true;
  $('logout').hidden = true;
  $('login').hidden = false;
  message('Вы вышли из пульта.', false, 'login-message');
  busy(false);
  $('login-form').elements.email.focus();
});
async function loadData() {
  const tables = ['players', 'news', 'matches', 'seasons', 'league_settings'];
  const values = await Promise.all(tables.map(t => api.list(t)));
  state.records = Object.fromEntries(tables.map((t,i) => [t,values[i]]));
  state.me = await api.rpc('member_me');
  $('members-tab').hidden = state.me.role !== 'owner';
  if (state.me.role === 'owner') state.records.members = await api.rpc('owner_members');
}
$('reload').addEventListener('click', async () => {
  if (state.busy || !mayLeave()) return;
  busy(true);
  message('Обновляем данные…');
  try {
    await loadData();
    state.dirty = false;
    renderList();
    renderEditor();
    message('Данные загружены из базы.');
  } catch(error) { message(error.message, true); }
  finally { busy(false); }
});
$('sections').addEventListener('click', event => {
  const button = event.target.closest('[data-section]');
  if (!button || state.busy || button.dataset.section === state.section || !mayLeave()) return;
  state.section = button.dataset.section;
  state.selected = null;
  state.dirty = false;
  $('search').value = '';
  message('');
  showSection();
});
$('search').addEventListener('input', renderList);
function showSection() {
  for (const button of $('sections').querySelectorAll('button')) button.setAttribute('aria-pressed', String(button.dataset.section === state.section));
  $('list-title').textContent = names[state.section];
  renderList();
  renderEditor();
}
function recordTitle(record) {
  return record.nickname || record.display_name || record.title || `Игровой день ${String(record.day).padStart(2,'0')}`;
}
function renderList() {
  $('records').replaceChildren();
  const search = $('search').value.trim().toLocaleLowerCase('ru');
  const records = state.records[state.section] || [];
  for (const record of records.filter(r => recordTitle(r).toLocaleLowerCase('ru').includes(search))) {
    const button = node('button', null, 'record');
    button.type = 'button';
    button.setAttribute('aria-current', String(record.id === state.selected));
    if (record.avatar) {
      const src = avatarUrl(record.avatar, location.href);
      if (src) { const img = node('img'); img.src = src; img.alt = ''; img.referrerPolicy = 'no-referrer'; button.append(img); }
    }
    const text = node('span');
    text.append(node('strong', recordTitle(record)));
    text.append(node('small', state.section === 'members' ? `${record.email} · ${record.status} · ${record.role}` : state.section === 'players' ? 'Профиль · ' + record.id : record.publication_status === 'published' ? 'Опубликовано в базе' : 'Черновик'));
    button.append(text);
    button.addEventListener('click', () => {
      if (state.busy || !mayLeave()) return;
      state.selected = record.id;
      state.dirty = false;
      message('');
      renderList();
      renderEditor();
      const heading = $('editor').querySelector('h2');
      heading?.focus({preventScroll: true});
      if (matchMedia('(max-width:768px)').matches) $('editor').scrollIntoView({behavior: matchMedia('(prefers-reduced-motion:reduce)').matches ? 'instant' : 'smooth', block:'start'});
    });
    $('records').append(button);
  }
  if (!$('records').children.length) $('records').append(node('p', 'Ничего не найдено.', 'empty'));
}
function field(form, label, name, value, {type = 'text', full = false, required = false, hint = '', options, readonly = false} = {}) {
  const wrap = node('label', label, full ? 'full' : '');
  const control = node(options ? 'select' : type === 'textarea' ? 'textarea' : 'input');
  control.name = name;
  if (options) for (const [v,t] of options) { const option = node('option',t); option.value=v; control.append(option); }
  else if (type === 'textarea') control.rows = name === 'paragraphs' ? 10 : 3;
  else { control.type = type; if (type === 'number') { control.min='0'; control.step='1'; } }
  control.value = value ?? '';
  control.required = required;
  control.readOnly = readonly;
  if (name === 'nickname') control.maxLength = 80;
  wrap.append(control);
  if (hint) wrap.append(node('small', hint));
  form.append(wrap);
  return control;
}
function renderEditor() {
  const editor = $('editor');
  editor.replaceChildren();
  const record = (state.records[state.section] || []).find(r => r.id === state.selected);
  if (!record) { editor.append(node('p','Выберите запись для просмотра или редактирования.','empty')); return; }
  const title = node('h2',recordTitle(record)); title.tabIndex=-1;
  editor.append(title, node('span',`${names[state.section]} / ${record.id}`,'badge'));
  if (state.section === 'matches') { renderMatch(record); return; }
  if (state.section === 'members') { renderMember(record); return; }
  const section = state.section;
  const form = node('form');
  const grid = node('div',null,'form-grid');
  if (section === 'players') {
    const img = node('img', null, 'portrait');
    img.alt = record.nickname; img.referrerPolicy='no-referrer';
    const src = avatarUrl(record.avatar,location.href); if (src) img.src=src; else img.hidden=true;
    editor.append(img);
    field(grid,'Ник','nickname',record.nickname,{required:true});
    field(grid,'Порядок в составе','display_order',record.display_order,{type:'number',required:true,hint:'От 0. Меньшее число — раньше в списке.'});
    field(grid,'Фотография','avatar',record.avatar,{full:true,required:true,hint:'Путь assets/имя.jpg или HTTPS-ссылка. Загрузка файлов будет отдельным шагом.'});
    field(grid,'Цитата игрока','quote',record.quote,{type:'textarea',full:true});
  } else {
    field(grid,'Заголовок','title',record.title,{full:true,required:true});
    field(grid,'Краткий заголовок','short_title',record.short_title,{full:true,hint:'Для компактной карточки на мобильном.'});
    field(grid,'Подпись','label',record.label);
    field(grid,'Порядок в ленте','display_order',record.display_order,{type:'number',required:true});
    field(grid,'Краткое описание','excerpt',record.excerpt,{type:'textarea',full:true});
    field(grid,'Текст новости','paragraphs',record.paragraphs.join('\n\n'),{type:'textarea',full:true,required:true,hint:'Разделяйте абзацы пустой строкой. Обычный текст, без HTML.'});
    field(grid,'Цитата игрока','quote_player_id',record.quote_player_id,{options:[['','Без цитаты'],...state.records.players.map(p => [p.id,p.nickname])]});
    field(grid,'Статус в базе','publication_status',record.publication_status,{options:[['draft','Черновик'],['published','Опубликовано']],hint:'Публичный сайт пока не подключён к базе.'});
  }
  const actions = node('div',null,'actions');
  const save = node('button','Сохранить в базе →','primary'); save.type='submit';
  const reset = node('button','Отменить правки','quiet'); reset.type='button';
  reset.addEventListener('click', () => { if (mayLeave()) {state.dirty=false; renderEditor(); message('');} });
  actions.append(save,reset);
  form.append(grid,actions);
  form.addEventListener('input', () => {state.dirty=true; message('Есть несохранённые изменения.');});
  form.addEventListener('change', () => {state.dirty=true;});
  form.addEventListener('submit', async event => {
    event.preventDefault();
    if (state.busy) return;
    let values;
    try {
      const fields = Object.fromEntries(new FormData(form));
      values = section === 'players' ? playerValues(fields,location.href) : newsValues(fields);
    } catch(error) {message(error.message,true); return;}
    busy(true); message('Сохраняем…');
    try {
      const saved = await api.update(section,record,values);
      state.records[section] = state.records[section].map(r => r.id === record.id ? saved : r).sort((a,b) => a.display_order-b.display_order || a.id.localeCompare(b.id));
      state.dirty=false;
      renderList(); renderEditor();
      message('Сохранено в базе. На публичном сайте изменения появятся после его подключения.');
    } catch(error) {message(error.message,true);}
    finally {busy(false);}
  });
  editor.append(form);
}
function renderMatch(record) {
  const season=state.records.seasons.find(s => s.id === record.season_id);
  const player=state.records.players.find(p => p.id === record.mvp_player_id);
  const facts=node('dl',null,'match-facts');
  const date=record.match_date ? record.match_date.split('-').reverse().join('.') : 'Не назначена';
  for (const [label,value] of [['Сезон',season?.label || record.season_id],['Дата',date],['Статус',record.status==='completed'?'Завершён':'Запланирован'],['MVP',player?.nickname || 'Не выбран']]) {
    const box=node('div'); box.append(node('dt',label),node('dd',value)); facts.append(box);
  }
  $('editor').append(facts,node('p','Здесь можно открыть и закрыть голосование. Итогового MVP подтверждает главный администратор. Редактор составов и карт пока не подключён.','notice'));
  renderBallotControls(record);
}
// Enable only after all handlers are registered. Classic bundle also loads from local files.
$('login-form').querySelector('button[type=submit]').disabled = false;
message('', false, 'login-message');

function renderMember(record) {
 const form=node('form'),grid=node('div',null,'form-grid');
 const isOwner=record.role==='owner';
 $('editor').append(node('p',record.email,'muted'));
 if(isOwner) $('editor').append(node('p','Главный администратор. Ваши права защищены; здесь можно привязать свой игровой профиль для голосования.','notice'));
 else {
  field(grid,'Статус участия','status',record.status,{options:[['pending','Ожидает подтверждения'],['approved','Подтверждён'],['blocked','Заблокирован']]});
  field(grid,'Права','role',record.role,{options:[['participant','Участник'],['admin','Администратор']]});
 }
 field(grid,'Игровой профиль','player_id',record.player_id,{full:true,options:[['','Не привязан'],...state.records.players.map(p=>[p.id,p.nickname])],hint:'Один игрок — один аккаунт. После назначения привязка закрепляется. Админ без привязки управляет сайтом, но не голосует.'});
 const save=node('button',isOwner?'Привязать мой профиль':'Сохранить доступ','primary');save.type='submit';
 form.append(grid,save);form.oninput=()=>{state.dirty=true;};
 form.onsubmit=async event=>{
  event.preventDefault();if(state.busy)return;const data=Object.fromEntries(new FormData(form));busy(true);
  try{await api.rpc('owner_update_member',{p_user_id:record.id,p_status:isOwner?'approved':data.status,p_role:isOwner?'admin':data.role,p_player_id:data.player_id||null});state.dirty=false;await loadData();renderList();renderEditor();message('Права сохранены. Они применяются на сервере сразу.');}
  catch(error){message(error.message,true);}finally{busy(false);}
 };
 $('editor').append(form);
}
async function renderBallotControls(record) {
 const box=node('section',null,'ballot-controls');box.append(node('h3','Голосование за MVP'));$('editor').append(box);
 if(record.status!=='completed'||record.publication_status!=='published'){box.append(node('p','Голосование доступно для завершённого опубликованного матча.','muted'));return;}
 try{
  const ballot=await api.rpc('mvp_ballot',{p_match_id:record.id});if(!box.isConnected)return;
  const labels={not_open:'Ещё не открыто',open:'Идёт голосование. Результаты скрыты.',closed:'Голосование закрыто',finalized:'MVP подтверждён'};
  box.append(node('p',labels[ballot.status],'badge'));
  async function action(kind,winner=null){
   if(state.busy)return;busy(true);message('Сохраняем…');
   try{await api.rpc('manage_mvp_ballot',{p_match_id:record.id,p_action:kind,p_winner_id:winner});await loadData();renderList();renderEditor();message(kind==='finalize'?'MVP подтверждён. Очки пересчитаны в базе; старые статические таблицы сайта пока не синхронизированы.':'Состояние голосования обновлено.');}
   catch(error){message(error.message,true);}finally{busy(false);}
  }
  if(ballot.status==='not_open'){const b=node('button','Открыть голосование','primary');b.onclick=()=>action('open');box.append(b);}
  if(ballot.status==='open'){const b=node('button','Закрыть и подсчитать голоса','primary');b.onclick=()=>action('close');box.append(b);box.append(node('p','После закрытия голоса изменить нельзя. Результаты фиксируются.','muted'));}
  if(ballot.results){
   for(const r of ballot.results){const c=ballot.candidates.find(p=>p.id===r.player_id);box.append(node('p',`${r.player_id===ballot.winner_player_id?'★ ':''}${c?.nickname||r.player_id} — ${r.votes}`));}
  }
  if(ballot.status==='closed'&&state.me.role==='owner'){
   const best=Math.max(0,...ballot.results.map(r=>r.votes));
   if(best>0){const form=node('form');const leaders=ballot.results.filter(r=>r.votes===best).map(r=>[r.player_id,ballot.candidates.find(c=>c.id===r.player_id)?.nickname||r.player_id]);field(form,'Подтвердить MVP','winner',leaders[0][0],{options:leaders,hint:'Выберите лидера. При равенстве голосов решение за вами. Повторное начисление исключено.'});const b=node('button','Подтвердить MVP и начисление','primary');b.type='submit';form.append(b);form.onsubmit=event=>{event.preventDefault();action('finalize',new FormData(form).get('winner'));};box.append(form);}
   else box.append(node('p','Нет действительных голосов. Награда не начисляется.','muted'));
  }
 }catch(error){if(box.isConnected)box.append(node('p',error.message,'status-error'));}
}

} catch (error) {
const message = document.getElementById('login-message');
if (message) { message.textContent = 'Не удалось запустить форму входа. Обновите страницу; если ошибка повторяется, сообщите нам.'; message.className = 'status-error'; }
}
})();
